# Build All
all: errors-all symbol-all listeners-all analysers-all main-all

# Cleans all
clean:

# Specific Rules
errors-all:
	$(MAKE) -C errors all

symbol-all:
	$(MAKE) -C symbol_table all

analysers-all:
	$(MAKE) -C analysers all

main-all:
	$(MAKE) -C main all

listeners-all:
	$(MAKE) -C listeners all
